### ISSUE TITLE
calculate cost mix of recent housing.

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/RegHsg#110]
Re; Robert McCartney request: In a follow-up email, he asked how new housing units are currently distributed across cost bands:

The report finds the need is to produce 38 percent in the lowest and low cost bands, and 40 percent in the low-middle and middle bands. That means 78 percent altogether.  But what percent are they getting now? I’d like to illustrate how much of a shift that would be.  

We'll look at units built after 2010 and look at the distribution using the ACS microdata.

**Comment by ptatian** [comment]
SAS log: L:\Libraries\RegHsg\Prog\Housing_needs_units_targets.log
