### ISSUE TITLE
Compile data for region from https://preservationdatabase.org/

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/RegHsg#2]
download for whole metro area or states if easier. We would like to be able to understand where properties are located, how many units are subsidized (at what level if known), subsidy programs involved, and any expiration dates for the subsidies. 

We want all jurisdictions in the COG region: 

DC (11001)
 Charles Couty(24017)
 Frederick County(24021)
 Montgomery County (24031)
 Prince George's County(24033)
 Arlington County (51013)
 Fairfax County (51059)
 Loudoun County (51107)
 Prince William County (51153)
 Alexandria City (51510)
 Fairfax City (51600)
 Falls Church City (51610)
 Manassas City (51683)
 Manassas Park City (51685)

**Comment by lhendey** [comment]
@Woliver01 - charge the holding account for now. 100001-0001-010-00002

**Comment by lhendey** [comment]
@Woliver01 - how are you doing on this issue?

**Comment by Woliver01** [comment]
@lhendey I'm going to commit some changes this afternoon, along with any issues I may have run in to.
