### ISSUE TITLE
Clean DC public records Black Knight data

### ISSUE THREAD

**Issue by maggiesu0725** [NeighborhoodInfoDC/RegHsg#23]

**Comment by lhendey** [comment]
@maggiesu0725 

These two files document the DC use codes an our cross-walk to ui_proptype which should be helpful for your cleaning process. let me know if you have questions. cc @cdavisurban @sstrochak 

file:///L:\Libraries\Realprop\Doc\UseCode%20&%20UI_proptype.xls

file:///L:\Libraries\Realprop\Doc\UseCodeDesc.xls

**Comment by maggiesu0725** [comment]
L:\Libraries\RegHsg\Prog\clean-DC.html
