### ISSUE TITLE
estimate sort-of natural affordable for rental stock

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/RegHsg#34]
@maggiesu0725 - please use the single year 2013-2017 ipums files (as in those used for projections) but **including vacant data**. to calculate: 

- [x] for cog region and jurisdiction: number of 4+ rental under $1200 (rentgrs) that's, less than 30, 30-60 years old and more than 60 years old. (should inflation adjust rents)

- [x]  for cog region and jurisdiction: number of 1-4 unit rental properties under $1200 month. less than 30, 30-60 years old and more than 60 years old and total.  (should inflation adjust rents)

my program housing_needs_units_targets.sas (currently on branch analysis-#21 ) uses the 2013-17 IPUMS (including vacant) and may have good base code for this work. 

target due date: 2/8-11

**Comment by maggiesu0725** [comment]
batched submitted. L:\Libraries\RegHsg\Prog\Natural affordable rental stock
