### ISSUE TITLE
Fix errors in Preservation_database.sas and COGRegion_subsidies.sas

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/RegHsg#35]
@Woliver01 The two programs **Preservation_database.sas** and **COGRegion_subsidies.sas** did not run properly when they were batch submitted on L:. 

For **Preservation_database.sas**, it mostly ran fine but at the end the *revisions=* parameter in the *%Finalize_data_set()* macro caused an error because the message was enclosed in quotes. 

```
ERROR: The name ?? is not a valid SAS name.
NOTE: Line generated by the macro variable "REVISIONS".
984         ""New file"
               __
               388
                 __
                 202
```

The *revisions=* message should not be enclosed in quote marks ("). Just put it inside the *%str( )* function. 

```
revisions=%str(New file),
```

Is the **COGRegion_subsidies.sas** program needed? This program accesses a temporary data set called **all_finalize**, but since that data set is not created in the program, it produces an error. 

```
104        proc summary data=all_finalize (where=(PropertyStatus="Active"));
ERROR: File WORK.ALL_FINALIZE.DATA does not exist.
105        	class COGregion CountyCode ;
ERROR: No data set open to look up variables.
```

If this program was just temporary while you were working some things out, we should delete it.  But if the program is doing something we need, then it should be corrected so that it runs properly when you batch submit it. 

Please create a new GitHub branch (bugfix-#35) to commit the changes for the above fixes. Please create a pull request and ask for a review when you are ready.  

When you are checking programs, you should not work only in interactive SAS. You also have to batch submit the program file on your D: drive so that you can be sure that each runs as a stand-alone program. Please remember to check the LOG files carefully after every batch submit. If there are ERROR messages, then they need to be addressed. If you don't know how to address them, please ask for help. 

Thank you. Please let @lhendey, @rpitingolo, or me know if you have any questions.

**Comment by Woliver01** [comment]
@ptatian The COGRegion program was temporary and @lhendey suggested I ask you how to go about next steps regarding that program. I can fix the Preservation_database program and resubmit it on it's own and make a separate issue for the COGregion program.
