### ISSUE TITLE
Change assisted unit count vars from character to numeric in RegHsg.Natlpres_activeandinc_prop

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/RegHsg#46]
@Woliver01 The assisted unit counts for S236 and possibly other programs are being read into **RegHsg.Natlpres_activeandinc_prop** as character variables, rather than numeric. Please review the format and input statements in the program and make sure that the format for variables named *..._assistedunits* is best12. and the input statement entry does **not** have a $ after it. 

You should also update the *revisions=* message in the *%Finalize_data_set()* macro to 

```
revisions=%str(Correct character vars for assisted unit counts.),
```

Please let me know if you have any questions.

**Comment by Woliver01** [comment]
@ptatian Is this issue safe to close?

**Comment by ptatian** [comment]
@Woliver01 As I mentioned in my review, you need to add the path to the LOG file on L: as a comment in the issue before we can close it.

**Comment by Woliver01** [comment]
@ptatian I understood the message Rob sent out to mean to leave the LOG on the original issue. I'll post the LOG here but in the future should I be putting the log on pull requests going forward?

**Comment by Woliver01** [comment]
Log path: **L:\Libraries\RegHsg\Prog\Subsidized_unit_counts.log**

**Comment by ptatian** [comment]
@Woliver01 You understood correctly. But *this* is the original issue (#46). Also, that's not the right log file.  (That's not the program you submitted to finish the work on this issue.)

**Comment by Woliver01** [comment]
@ptatian Log Path(corrected): **L:\Libraries\RegHsg\Prog\Preservation_database,log**

**Comment by Woliver01** [comment]
Log Path corrected: **L:\Libraries\RegHsg\Prog\**Preservation_database.log**

**Comment by Woliver01** [comment]
**L:\Libraries\RegHsg\Prog\Preservation_database.log**

**Comment by ptatian** [comment]
@Woliver01 Looks good. OK to close the issue. Thanks.
