### ISSUE TITLE
Housing market analysis - Demographic trends

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/RegHsg#56]
Produce data tables in Excel on demographic trends in the RHF-defined Washington region. 

**Needed by: Feb 22.**

- Number of persons, region total and by jurisdiction, 1970, 1980, 1990, 2000, 2010, 2017 [a, b]
- Components of population change: Natural growth vs. in-migration (Would like to have some sort of trend data here. Please check what is available.) [b]
- Persons, 2000, 2010, 2017 [c]
  - ...by age
  - …by race/ethnicity
  - …by immigration status

- Number of households 1970, 1980, 1990, 2000, 2010, 2017 [a, b]
- Households, 2000, 2010, 2017 [c]
  - …by size
  - …by types [singletons, 2+ unrelated persons (only), couples without kids, other families, other HHs]
  - …by income [use income ranges defined in **Prog/Housing_needs_units_targets.sas**, *inc_cat.* format.]

Sources: [a] Neighborhood Change Database (NCDB); [b] [Census population estimates](https://www.census.gov/programs-surveys/popest/data/data-sets.2017.html); [c] IPUMS Census/ACS microdata.

Notes:
- All data are counts (numbers of persons, households) for the entire region unless other specified. 
- Years should define table columns; other dimension are rows.
- Always include a total row in the table. 
- 2017 ACS microdata person and household weights should be adjusted to match totals in census population estimates. 
- Census does not estimate numbers of households; only housing units. Use the overall housing vacancy rate for the region to convert the 2017 housing unit count to a household count.

**Comment by maggiesu0725** [comment]
@rpitingolo this seems more straightforward than the other two, i will work on this first.

**Comment by rpitingolo** [comment]
@maggiesu0725 OK, thank you. Please make the edit that Peter requested on the permit read-in program first so we can close that issue.

**Comment by maggiesu0725** [comment]
- [ ]  Number of persons

- [ ]  Components of population change: Natural growth vs. in-migration

- [ ] Persons by age, race and immigration status

- [ ] Number of households

- [ ] Household by size, type and income category

**Comment by maggiesu0725** [comment]
@ptatian  @rpitingolo do you know if we have a program that summarizes 2+ unrelated persons (only) households? I'm not sure how to identify these. ?

**Comment by maggiesu0725** [comment]
I can't think of a better way than generating a separate flag file and merge back to the main dataset. ? @rpitingolo @ptatian

**Comment by ptatian** [comment]
We did something like this for the DMPED large housing unit study. We also have a “family” dataset for the IPUMS data that has some summary indicators. I don’t know if that has been run for the latest data and it might not have exactly what we need.


________________________________

**Comment by maggiesu0725** [comment]
L:\Libraries\RegHsg\Prog\Demographic trends.log
