### ISSUE TITLE
Housing market analysis - Housing trends

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/RegHsg#58]
Produce data tables in Excel on housing trends in the RHF-defined Washington region.

**Needed by: Feb 22.**

- Housing units (occupied + vacant), 2000, 2010, 2017 [a]
  - ... by structure type (single-family dwellings, duplex, small multifamily, large multifamily) 
  - … by bedroom size
- Building permits by type of structure, 2000 – 2017 [b]
- Homeowner households, 2000, 2010, 2017 [a]
- Homeownership rates, 2000, 2010, 2017 [a]
- Homeowner housing vacancy rates, 2000, 2010, 2017 [a]
- Sale prices (July, constant 2018 $), 2000 – 2018 [c]
- For-sale housing market inventory (July), 2000 - 2018 [d]
- Cost burdens for homeowners, 2000, 2010, 2017 [a]
- Renter households, 2000, 2010, 2017 [a]
- Rental vacancy rates, 2000, 2010, 2017 [a]
- Rents for single-family and multifamily residences (July, constant 2018 $), 2000 – 2018 [e]
- Cost burdens for renters, 2000, 2010, 2017 [a]

Data sources: [a] IPUMS Census/ACS; [b] Census building permits (data set being created in Census library); [c] [Zillow](https://www.zillow.com/research/data/) median sales price (seasonally adjusted $), July, Washington MSA; [d] [Zillow](https://www.zillow.com/research/data/) monthly for-sale inventory (smooth, seasonally adjusted), July, Washington MSA; [e] [Zillow](https://www.zillow.com/research/data/) ZRI time series: SFR ($) and ZRI time series: multifamily ($), July, Washington MSA.

Notes:
- All data are counts (numbers of persons, households) for the entire region unless other specified.
- Years should define table columns; other dimension are rows.
- Always include a total row in the table. 
- 2017 ACS microdata household weights should be adjusted to match totals in [Census population estimates](https://www.census.gov/programs-surveys/popest/data/data-sets.2017.html).

**Comment by maggiesu0725** [comment]
- [ ]  Housing units (occupied + vacant), 2000, 2010, 2017 [a]
  
  * ... by structure type (single-family dwellings, duplex, small multifamily, large multifamily)
  * … by bedroom size
- [ ]  Building permits by type of structure, 2000 – 2017 [b]
- [ ] Homeowner households, 2000, 2010, 2017 [a]
- [ ]  Homeownership rates, 2000, 2010, 2017 [a]
- [ ] Homeowner housing vacancy rates, 2000, 2010, 2017 [a]
- [ ] Sale prices (July, constant 2018 $), 2000 – 2018 [c]
- [ ] For-sale housing market inventory (July), 2000 - 2018 [d]
- [ ] Cost burdens for homeowners, 2000, 2010, 2017 [a]
- [ ] Renter households, 2000, 2010, 2017 [a]
- [ ] Rental vacancy rates, 2000, 2010, 2017 [a]
- [ ] Rents for single-family and multifamily residences (July, constant 2018 $), 2000 – 2018 [e]
- [ ] Cost burdens for renters, 2000, 2010, 2017 [a]

**Comment by maggiesu0725** [comment]
so I just realized there's no owner cost variable in 2000 ipums dataset. Should I just add up some of the costs in there (costelec, costfuel, costgas, costwatr, propinsr) or find another source for this information? @ptatian @rpitingolo

**Comment by rpitingolo** [comment]
@maggiesu0725 it looks like the OWNCOST variable exists in 2000 but for a reason I don't know we don't have in the Warehouse. I think the most prudent thing to do would be to download that variable from iPums and merge it on. https://usa.ipums.org/usa-action/variables/OWNCOST#universe_section

@ptatian do you agree?

**Comment by ptatian** [comment]
@maggiesu0725 was already thinking of redownloading the 2000 data - so this could be another reason to do that. You do have to be careful if you add things up because not all of the costs are monthly.

**Comment by rpitingolo** [comment]
L:\Libraries\RegHsg\Prog\Housing market analysis.log
