### ISSUE TITLE
Spatial Join + Vacant Lots Analysis

### ISSUE THREAD

**Issue by pspauster** [NeighborhoodInfoDC/RegHsg#60]

**Comment by sstrochak** [comment]
hi @pspauster - I need to use DC parcel data for the upzoning analysis (has to be done on a regional scale). I need the parcel data with as clean/complete lot size and number of units variables as possible. Does that happen in this step, after you have done the spatial join with the parcel file? Or can I just use the output from `clean-montgomery.Rmd`?

**Comment by pspauster** [comment]
I don't fill in the missing lot size until after the spatial join in the post-clean.rmd

**Comment by pspauster** [comment]
@sstrochak

**Comment by sstrochak** [comment]
Is this the file I should use?
```
saveRDS(pzjoin_df1,
        paste0(jdir, 
               "parceljoined-",
               filepath,
               "-data.Rdata"))
```

**Comment by pspauster** [comment]
I think so, yes. But I am not sure that file has filled back in the observations that didn't join yet. I was trying to figure out how to do that.

**Comment by sstrochak** [comment]
ok cool, let me know if I can help/when that is done!

**Comment by pspauster** [comment]
okay. I probably won't be able to do that until tomorrow morning b/c I'm out. If you need it more urgently, I was planning on using st_disjoint or st_difference to grab them and then bind_rows to put them back in. Have you used either of those before?

**Comment by sstrochak** [comment]
I haven't, but I can take a look at that with you tomorrow morning

**Comment by maggiesu0725** [comment]
@lhendey so I discovered for Rockvile and Gaithersburg, some of the vacant lots are zoned by Montgomery code, although not a lot. And then are quite a few other codes that are not in any of the Jurisdictions' zoning designations. What's your thoughts on these? Should I use Montgomery to fill the unmatched?

**Comment by pspauster** [comment]
@maggiesu0725 I think I am ready to submit a pull request, so let me know when you are done with your file and we can do that!

**Comment by maggiesu0725** [comment]
I’m done with my file I thought you are going to combine the two? If not we can just keep the two programs separate and run them separately. One thing though, I thought you are coming up with new categorization for dwelling types? And you can create a pull request when ever, your new commits will show up in the pull request. @pspauster

**Comment by sstrochak** [comment]
@lhendey is this what you needed me to review for R ?

**Comment by lhendey** [comment]
@sstrochak yes that would be good, but i'm about done with a review of the code so maybe wait until they clean it up a little more.
