### ISSUE TITLE
Fairfax vacant lot analysis

### ISSUE THREAD

**Issue by cdavisurban** [NeighborhoodInfoDC/RegHsg#70]

**Comment by lhendey** [comment]
@cdavisurban - can i get a status update on this? is it ready for review?

**Comment by cdavisurban** [comment]
@lhendey yes it is. for some reason my commit wasn't pushed to this issue, but to analysis-#77

**Comment by lhendey** [comment]
@cdavisurban - @sstrochak merged #77 so we'd need to review the master?
