### ISSUE TITLE
Revisions to housing market employment data

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/RegHsg#75]
Need to ask for some changes to the employment data previously prepared under issue #57.

**Prog\iPums Employment Trends.sas**

The breakdowns in **workers_byyear.csv** were not exactly what I was looking for. I would like to have adults (18+ years) by these categories.
- civilian employed (at work or have a job)
- in military (at work or have a job)
- students
- unemployed
- [other] not in labor force

The above should be exhaustive and mutually exclusive, that is, every adult should be in one, and only one, of the above groups. For students, it's a little ambiguous, but I would say if someone is a student then we should count them in that group, even if they are working. 

I would also like to ask for an additional breakdown of *workers average commuting time by jurisdiction and total for the region*. 

***

**Prog\Employment Trends.sas**

Would like to ask for a change on the BLS industry breakdowns by NAICS. There are a number of subtotals embedded and it would be helpful to break them out into mutually exclusive groups as follows.

- Construction
- Other goods-producing [total goods producing minus construction]
- Professional and business services
- Education and health services
- Trade, transport, and utilities
- Leisure and hospitality
- Financial
- Information services
- Other services [total services minus service groups listed above]

**Comment by ptatian** [comment]
@rpitingolo Please look at the requested changes for the employment data. Should be straight forward but let me know if you have any questions.

**Comment by rpitingolo** [comment]
@ptatian going to take a look now.

**Comment by rpitingolo** [comment]
L:\Libraries\RegHsg\Prog\iPums Employment Trends.log
L:\Libraries\RegHsg\Prog\Employment Trends.log
