### ISSUE TITLE
fixes to DC clean

### ISSUE THREAD

**Issue by lhendey** [NeighborhoodInfoDC/RegHsg#79]
- [x] add  units for apartments

- [x] fix dropping x_coord, y_coord

**Comment by lhendey** [comment]
@sstrochak i opened this issue for fixes to DC clean. I think need to merge a couple of DC files together to get the apartment units so i'll do that in sas and output a CSV for you.

**Comment by sstrochak** [comment]
@lhendey thanks, I'm fixing the coordinates now

**Comment by lhendey** [comment]
@sstrochak - for the record from the Master Address Repository I'm getting 159,898 rental units and 49,881 condo units.

**Comment by sstrochak** [comment]
@lhendey does that rental units total include single family and condos that are rented out? from our cleaned parcel data we have 58,145 condo units

**Comment by lhendey** [comment]
@sstrochak i haven't merged yet with the parcel data there was a rental vs. condo flag on our unit level address file so I'm guessing the condos (whether rented or owner occupied are definitely condo). probably less clear on the prop type for rental.

**Comment by lhendey** [comment]
@sstrochak also sas is being really freaking slow.

**Comment by lhendey** [comment]
@sstrochak in our summary files from parcel base we have 60172 condo units as of Q3 2018

**Comment by lhendey** [comment]
@sstrochak  yipeng commit https://github.com/NeighborhoodInfoDC/RegHsg/pull/74/commits/c724222c77da99f0e5e7df97aecb27429c31c590 has some changes to clean-DC too.

**Comment by sstrochak** [comment]
@lhendey should I work off her version of clean-DC?
