### ISSUE TITLE
calculate gentrification and displacement risk

### ISSUE THREAD

**Issue by maggiesu0725** [NeighborhoodInfoDC/RegHsg#8]
recreate https://www.portlandoregon.gov/bps/article/454027

**Comment by maggiesu0725** [comment]
@ptatian @lhendey Hi Peter and Leah, I'm trying to calculate change between 2000 and 2016 by tract and since tract boundaries have changed, I think I'm going to pull 2016 by 2000 tract and then calculate the difference in the 2000 tract boundary and use a crosswalk to convert the change to 2010 tract boundary? Or is there a better way? Thanks!

**Comment by lhendey** [comment]
@maggiesu0725 please use the NCDB as discussed. @ptatian

**Comment by lhendey** [comment]
L:\Libraries\RegHsg\Prog\Vulnerable to gentrification_Jurisdiction.log
